#TEST123
name: Deploy Application For Production

on:
  push:
    branches:
      - development

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    outputs:
      deployment-matrix: ${{ steps.export-deployment-matrix.outputs.deployment-matrix }}
    steps:
      - uses: actions/checkout@v4


      - name: Configure PHP 8.3
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.3
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml, sqlite3

      - name: Composer install
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Compile CSS and Javascript
        run: |
          sudo npm install
          sudo npm run build

      - name: Create deployment artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules --exclude=tests *

      - name: Store artifact for distribution
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ${{ github.sha }}.tar.gz

      - name: Export deployment matrix
        id: export-deployment-matrix
        run: |
          JSON="$(cat ./development-server-config.json)"
          JSON="${JSON//'%'/'%25'}"
          JSON="${JSON//$'\n'/'%0A'}"
          JSON="${JSON//$'\r'/'%0D'}"
          echo "::set-output name=deployment-matrix::$JSON"

  prepare-release-on-servers:
    name: "${{ matrix.server.name }}: Prepare release"
    runs-on: ubuntu-latest
    needs: create-deployment-artifacts
    strategy:
      matrix:
        server: ${{ fromJson(needs.create-deployment-artifacts.outputs.deployment-matrix) }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-build
      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.SERVER_SSH }}
          port: ${{ matrix.server.port }}
          source: ${{ github.sha }}.tar.gz
          target: ${{ matrix.server.path }}/artifacts
          debug: true
      - name: Extract archive and create directories
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.SERVER_SSH }}
          port: ${{ matrix.server.port }}
          envs: GITHUB_SHA
          script: |
            # Create the release directory and set ownership
            sudo mkdir -p "${{ matrix.server.path }}/releases/${GITHUB_SHA}"
            sudo chown -R ubuntu:www-data ${{ matrix.server.path }}/releases
            
            # Extract the tar.gz archive to the release directory
            sudo tar xzf ${{ matrix.server.path }}/artifacts/${GITHUB_SHA}.tar.gz -C "${{ matrix.server.path }}/releases/${GITHUB_SHA}"
            
            # Ensure the necessary storage directories exist (but don't remove the existing storage folder)
            sudo mkdir -p ${{ matrix.server.path }}/storage/{app,public,framework,logs}
            sudo mkdir -p ${{ matrix.server.path }}/storage/framework/{cache,sessions,testing,views}
            sudo mkdir -p ${{ matrix.server.path }}/storage/database
            
            # Ensure the SQLite database file exists if you're using SQLite
            sudo touch ${{ matrix.server.path }}/storage/database/database.sqlite
            
            # Set the correct permissions for the storage directory and subdirectories
            sudo chmod -R 0777 ${{ matrix.server.path }}/storage
            sudo chown -R ubuntu:www-data ${{ matrix.server.path }}/storage
            
            # Set specific permissions for framework directories
            sudo chown -R ubuntu:www-data ${{ matrix.server.path }}/storage/framework
            
            # Ensure the bootstrap cache directory exists and set permissions
            sudo chown -R ubuntu:www-data ${{ matrix.server.path }}/releases/${GITHUB_SHA}/bootstrap/cache
            
            # Set appropriate permissions for the SQLite database
            sudo chmod 664 ${{ matrix.server.path }}/storage/database/database.sqlite
            sudo chmod -R 775 ${{ matrix.server.path }}/storage/database
            
            # Ensure the necessary directories exist
            sudo mkdir -p ${{ matrix.server.path }}/storage/framework/views
            sudo mkdir -p ${{ matrix.server.path }}/bootstrap/cache
            
            # Set correct ownership for storage and bootstrap/cache (to www-data)
            sudo chown -R ubuntu:www-data ${{ matrix.server.path }}/storage
            sudo chown -R ubuntu:www-data ${{ matrix.server.path }}/bootstrap/cache
            
            # Set the correct permissions for storage and cache directories
            sudo chmod -R 775 ${{ matrix.server.path }}/storage
            sudo chmod -R 775 ${{ matrix.server.path }}/bootstrap/cache

      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: app-build
          failOnError: false

  run-before-hooks:
    name: "${{ matrix.server.name }}: Before hook"
    runs-on: ubuntu-latest
    needs: [ create-deployment-artifacts, prepare-release-on-servers ]
    strategy:
      matrix:
        server: ${{ fromJson(needs.create-deployment-artifacts.outputs.deployment-matrix) }}
    steps:
      - name: Run before hooks
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
          RELEASE_PATH: ${{ matrix.server.path }}/releases/${{ github.sha }}
          ACTIVE_RELEASE_PATH: ${{ matrix.server.path }}/current
          STORAGE_PATH: ${{ matrix.server.path }}/storage
          BASE_PATH: ${{ matrix.server.path }}
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.SERVER_SSH }}
          port: ${{ matrix.server.port }}
          envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH
          script: |
            ${{ matrix.server.beforeHooks }}

  activate-release:
    name: "${{ matrix.server.name }}: Activate release"
    runs-on: ubuntu-latest
    needs: [ create-deployment-artifacts, prepare-release-on-servers, run-before-hooks ]
    strategy:
      matrix:
        server: ${{ fromJson(needs.create-deployment-artifacts.outputs.deployment-matrix) }}
    steps:
      - name: Activate release
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
          RELEASE_PATH: ${{ matrix.server.path }}/releases/${{ github.sha }}
          ACTIVE_RELEASE_PATH: ${{ matrix.server.path }}/current
          STORAGE_PATH: ${{ matrix.server.path }}/storage
          BASE_PATH: ${{ matrix.server.path }}
          LARAVEL_ENV: ${{ secrets.APP_ENV }}
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.SERVER_SSH }}
          port: ${{ matrix.server.port }}
          envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH,ENV_PATH,LARAVEL_ENV
          script: |
            sudo printf "%s" "$LARAVEL_ENV" > "${BASE_PATH}/.env"
            sudo ln -s -f ${BASE_PATH}/.env $RELEASE_PATH
            sudo rm -rf ${RELEASE_PATH}/storage
            sudo ln -s -f $STORAGE_PATH $RELEASE_PATH
            sudo ln -s -n -f $RELEASE_PATH $ACTIVE_RELEASE_PATH
            sudo service php8.3-fpm reload
            sudo chown -R ubuntu:www-data $ACTIVE_RELEASE_PATH
            cd ${ACTIVE_RELEASE_PATH}

            sudo php artisan migrate --force
            sudo php artisan cache:clear
            sudo php artisan auth:clear-resets
            sudo php artisan view:cache
            sudo php artisan queue:restart
            sudo php artisan optimize
            sudo php artisan storage:link
            sudo composer install --optimize-autoloader --no-dev

  run-after-hooks:
    name: "${{ matrix.server.name }}: After hook"
    runs-on: ubuntu-latest
    needs: [ create-deployment-artifacts, prepare-release-on-servers, run-before-hooks, activate-release ]
    strategy:
      matrix:
        server: ${{ fromJson(needs.create-deployment-artifacts.outputs.deployment-matrix) }}
    steps:
      - name: Run after hooks
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
          RELEASE_PATH: ${{ matrix.server.path }}/releases/${{ github.sha }}
          ACTIVE_RELEASE_PATH: ${{ matrix.server.path }}/current
          STORAGE_PATH: ${{ matrix.server.path }}/storage
          BASE_PATH: ${{ matrix.server.path }}
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.SERVER_SSH }}
          port: ${{ matrix.server.port }}
          envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH
          script: |
            export PATH=$PATH:/usr/local/bin:/home/ubuntu/.nvm/versions/node/v20.16.0/bin
            
            # Ensure correct permissions for package.json
            sudo chown -R ubuntu:www-data /var/www/buildbooker/releases/${{ github.sha }}/package.json
            sudo chown -R ubuntu:www-data /var/www/buildbooker/releases/${{ github.sha }}/package-lock.json
            
            
            # Ensure Puppeteer is installed locally
            cd /var/www/buildbooker/releases/${{ github.sha }}
            npm install puppeteer
            sudo chown -R ubuntu:www-data /var/www/buildbooker/releases/${{ github.sha }}/node_modules
            sudo chown -R ubuntu:www-data /var/www/buildbooker/releases/${{ github.sha }}/package-lock.json
            
            # Make sure `receipts` folder has right permissions
            sudo chown -R ubuntu:www-data /var/www/buildbooker/storage
            sudo chmod -R 755 /var/www/buildbooker/storage
            
            # Make REcceipts Folder
            # make release-specific receipts folder, inherit set-gid group
            sudo mkdir -p "${{ matrix.server.path }}/releases/${GITHUB_SHA}/storage/app/public/receipts"
            sudo chown -R ubuntu:www-data "${{ matrix.server.path }}/releases/${GITHUB_SHA}/storage"
            sudo chmod -R 2775 "${{ matrix.server.path }}/releases/${GITHUB_SHA}/storage"
  
            # No need to run Puppeteer directly here because it's handled in Laravel
            ${{ matrix.server.afterHooks }}
  

  clean-up:
    name: "${{ matrix.server.name }}: Clean up"
    runs-on: ubuntu-latest
    needs: [ create-deployment-artifacts, prepare-release-on-servers, run-before-hooks, activate-release, run-after-hooks ]
    strategy:
      matrix:
        server: ${{ fromJson(needs.create-deployment-artifacts.outputs.deployment-matrix) }}
    steps:
      - name: Run after hooks
        uses: appleboy/ssh-action@master
        env:
          RELEASES_PATH: ${{ matrix.server.path }}/releases
          ARTIFACTS_PATH: ${{ matrix.server.path }}/artifacts
        with:
          host: ${{ matrix.server.ip }}
          username: ${{ matrix.server.username }}
          key: ${{ secrets.SERVER_SSH }}
          port: ${{ matrix.server.port }}
          envs: RELEASES_PATH
          script: |
            cd $ARTIFACTS_PATH && sudo ls -t | tail -n +3 | xargs rm -rf
            cd $RELEASES_PATH && sudo ls -t -1 | tail -n +3 | xargs rm -rf
